version: '3'
services:
  client_app1:
    build: .
    ports:
      - "8082:8082"
    container_name: client_app1
    volumes:
      - "./public/swagger.json:/client_app/public/swagger.json"
      - ".env:/client_app/.env"
    networks:
      - myNetwork

networks:
  myNetwork:
    name: local