version: '3'
services:
  nginx_proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Путь к вашему конфигурационному файлу nginx.conf
    container_name: nginx_proxy
    networks:
      - myNetwork

networks:
  myNetwork:
    name: local