version: '3'
services:
  client_app1:
    build: ./client_geo1
    ports:
      - "8081:8081"
    container_name: client_app1
    volumes:
      - "./client_geo1/public/swagger.json:/client_app/public/swagger.json"
      - ".env:/client_app/.env"
    networks:
      - myNetwork

  server_geo1:
    build: ./geo1
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    container_name: server_geo1
    volumes:
      - "./geo1/.env:/server_app/.env"
    networks:
      - myNetwork 
      - myNetworkDB
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.4-alpine
    container_name: postgres_Geo1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - myNetworkDB

  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    networks:
      - myNetworkDB

networks:
  myNetworkDB:
  myNetwork:
    name: local
